# ---- Gradle JVM ----
# JVM args cho Gradle daemon. Ép encoding UTF-8 để không hỏng chú thích tiếng Việt.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# ---- Hiệu năng build ----
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# ---- AndroidX ----
android.useAndroidX=true
android.nonTransitiveRClass=true

# ---- Kotlin ----
kotlin.code.style=official
